In [1]:
a = [10,39,90,56,35]

In [2]:
list(enumerate(a))

[(0, 10), (1, 39), (2, 90), (3, 56), (4, 35)]

In [3]:
d = {'a': 1, "b": 2, "c": 5, "d": 6}

In [4]:
list(enumerate(d))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [5]:
for index, key in enumerate(d):
    print(index,".", key," : ", d[key], sep = "")

0.a : 1
1.b : 2
2.c : 5
3.d : 6


In [6]:
#Assignment
fruits_to_color = {"watermelon": "green", "pomegranate": "red", "peach": "orange","cherry": "red", "orange": "orange"}
#convert this into colors to fruit - with unique colors on lhs, rhs can have multiple values for the fruits.

### lambda fn
one liner functions

In [7]:
def fn(x,y):
    return x+y

In [8]:
fn(4,5)

9

In [9]:
f = lambda x, y: x+y

In [10]:
f(4,5)

9

In [11]:
g = lambda x: x**2

In [12]:
h = lambda x,y,z: (x+y+z)/3

In [13]:
h(1,32, 6)

13.0

In [14]:
i = lambda x,y,z,w: 3*(x**3)+2*(y**2) + z + w**(-1)

### map function
map will map the given function on each element of the iterable

In [15]:
a = lambda x: x**2

In [16]:
lst = [10,20,30]

In [17]:
list(map(a, lst))

[100, 400, 900]

In [18]:
for i in map(lambda x: x**3, lst):
    print(i)

1000
8000
27000


### reduce function
reduce(fun, iterable) will apply to the sequence and it returns a single value

In [19]:
from functools import reduce

In [20]:
lst.extend([1,5,6,10])

In [21]:
lst

[10, 20, 30, 1, 5, 6, 10]

In [22]:
reduce(lambda x,y: x-y, lst)

-62

Exercise : A store maintains a list of all customers with the customer number and the price of each item purchased by the customer. Find the total amount for each customer using lambda, map reduce 

In [23]:
orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,300.50,650.50)]]

In [24]:
orders[0][0], orders[1][0], orders[2][0]

(1, 2, 3)

In [25]:
[orders[0][0]]+[reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [26]:
reduce(lambda x,y: x+y, orders[1][1])

951.25

In [27]:
reduce(lambda x,y: x+y, orders[2][1])

1351.0

In [28]:
[orders[0][0]]+[reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [29]:
[orders[1][0]]+[reduce(lambda x,y: x+y, orders[1][1])]

[2, 951.25]

In [30]:
#replace orders[0] in the above line by 'a' because we want to map this lambda fn on each component of orders list
f = lambda a: [a[0]]+[reduce(lambda x,y: x+y, a[1])]

In [31]:
list(map(f, orders))

[[1, 1050.5], [2, 951.25], [3, 1351.0]]

----

### List Comprehensions
new_list = [return_value for i in lst]

new_list = [return_Value for i in lst if condition]

new_list = [return value if cond else return_value for i in lst]

In [32]:
l = [i**2 for i in [1,2,3]]
l

[1, 4, 9]

In [33]:
m = [i**10 for i in [10,20,30]]
m

[10000000000, 10240000000000, 590490000000000]

In [34]:
n = [i for i in range(10) if i%2==0]
n

[0, 2, 4, 6, 8]

In [35]:
n = [i**3 for i in range(10) if i%2==0]
n

[0, 8, 64, 216, 512]

In [36]:
o = ["even" if i%2==0 else "odd" for i in lst ]

In [37]:
o

['even', 'even', 'even', 'odd', 'odd', 'even', 'even']

### Zip fn

In [38]:
cost = [.424, .4221, .4228, .413]
cases = [10,20,40,30]

In [39]:
cost*cases

TypeError: can't multiply sequence by non-int of type 'list'

In [42]:
list(zip(cost,cases))

[(0.424, 10), (0.4221, 20), (0.4228, 40), (0.413, 30)]

In [43]:
for x,y in zip(cost, cases):
    print(x*y/sum(cases))

0.0424
0.08442
0.16912
0.12389999999999998


## Importing Libraries
Libraries or packages are the blocks of codes, the programmers have already done the programming, we'll just plug and play those functions.

In [44]:
import numpy

In [45]:
numpy.array([1,3,4])

array([1, 3, 4])

In [46]:
import numpy as np

In [47]:
np.array([1,2,4,5,6])

array([1, 2, 4, 5, 6])

In [48]:
from numpy import *

In [49]:
array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [50]:
from numpy import array

In [51]:
array([1,3,4,5,6])

array([1, 3, 4, 5, 6])

In [52]:
from functools import reduce

In [53]:
reduce(lambda x,y: x*y, [1,2,3,4,5,6])

720

### To install a library

In [54]:
#!pip install keras

In [128]:
#!conda install keras

In [129]:
def fn(x,y):
    return x+y

In [130]:
f = lambda x,y: x+y

In [131]:
fn(3,4)

7

In [132]:
f(3,4)

7

In [133]:
def fn(x):
    return x**2

In [134]:
g = lambda x: x**2

In [135]:
def fn(x):
    return x[0]

In [136]:
fn("Samridhi")

'S'

In [137]:
f = lambda x: x[0]

In [138]:
f("Samridhi")

'S'

Exercise : A store maintains a list of all customers with the customer number and the price of each item purchased by the customer. Find the total amount for each customer using lambda, map reduce 

In [139]:
orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,300.50,650.50)]]

In [140]:
[orders[0][0]]

[1]

In [141]:
[reduce(lambda x,y: x+y, orders[0][1])]

[1050.5]

In [142]:
[orders[0][0]] + [reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [143]:
[orders[1][0]] + [reduce(lambda x,y: x+y, orders[1][1])]

[2, 951.25]

In [144]:
[orders[2][0]] + [reduce(lambda x,y: x+y, orders[2][1])]

[3, 1351.0]

In [145]:
f = lambda a: [a[0]] + [reduce(lambda x,y: x+y, a[1])]

In [146]:
f(orders[0])

[1, 1050.5]

In [147]:
f(orders[1])

[2, 951.25]

In [148]:
f(orders[2])

[3, 1351.0]

In [149]:
list(map(f, orders))

[[1, 1050.5], [2, 951.25], [3, 1351.0]]

In [150]:
list(map(lambda x: x**2, [1,2,3]))

[1, 4, 9]

In [151]:
a = ['a','b', 'c']

In [152]:
b = [10,20,30]

In [153]:
list(zip(a,b))

[('a', 10), ('b', 20), ('c', 30)]

In [154]:
for x,y in zip(a,b): #this will iterate over the above list
    print(x*y)

aaaaaaaaaa
bbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccc


-----

### Numpy Arrays
- Numeric Python
- There can be character numpy arrays
- But functions like np.max, np.min - will throw exception on character arrays

In [155]:
import numpy as np

In [156]:
a = [1,2,3,4]
b = [10,20,30,40]

In [157]:
a+b #concatenation of lists

[1, 2, 3, 4, 10, 20, 30, 40]

In [158]:
lst = []
for x,y in zip(a,b):
    lst.append(x+y)

In [159]:
lst

[11, 22, 33, 44]

In [160]:
array_a = np.array(a)
array_b = np.array(b)

In [161]:
array_a

array([1, 2, 3, 4])

In [162]:
type(array_a)

numpy.ndarray

In [163]:
array_b

array([10, 20, 30, 40])

In [164]:
array_a + array_b #arrays will support element wise addition / multiplication / division  

array([11, 22, 33, 44])

In [165]:
type(np)

module

In [166]:
array_a.size #number of elements in the array

4

In [167]:
array_a.ndim

1

In [168]:
array_a.shape

(4,)

In [169]:
c = [[1,2,3], [4,5,6]]
arr = np.array(c)

In [170]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [171]:
arr.size

6

In [172]:
arr.shape

(2, 3)

In [173]:
arr.ndim

2

In [174]:
arr_3d = np.array([[[1,3], [2,4], [5,6]], [[10,20],[2,3], [4,5]]])

In [175]:
arr_3d

array([[[ 1,  3],
        [ 2,  4],
        [ 5,  6]],

       [[10, 20],
        [ 2,  3],
        [ 4,  5]]])

In [176]:
arr_3d.shape

(2, 3, 2)

In [177]:
arr_2d = np.array([array_a, array_b])

In [178]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [179]:
arr_2d[0,0]

1

In [180]:
arr_2d[-1,-1]

40

In [181]:
arr_2d[1, 2], arr_2d[-1, -2]

(30, 30)

In [182]:
arr_2d[-1, -3]

20

In [183]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [184]:
arr_2d=np.concatenate([arr_2d, np.array([range(4)]), np.array([range(10, 18, 2)])], axis = 0)
#axis = 0 row-wise concatenation
#axis = 1 col-wise concatenation

In [185]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [ 0,  1,  2,  3],
       [10, 12, 14, 16]])

In [186]:
list(range(4))

[0, 1, 2, 3]

In [187]:
np.array([range(4)])

array([[0, 1, 2, 3]])

In [188]:
list(range(10,18,2)) 

[10, 12, 14, 16]

In [189]:
np.array([range(10,18,2)])

array([[10, 12, 14, 16]])

In [190]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [191]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [192]:
np.array(range(10,18,2))

array([10, 12, 14, 16])

In [193]:
np.arange(10, 18, 2)

array([10, 12, 14, 16])

In [194]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [ 0,  1,  2,  3],
       [10, 12, 14, 16]])

In [195]:
x = np.arange(5,9,1)
x

array([5, 6, 7, 8])

In [196]:
x=x.reshape(4,1)
x

array([[5],
       [6],
       [7],
       [8]])

In [197]:
arr_2d = np.concatenate([arr_2d, x], axis = 1)

In [198]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40,  6],
       [ 0,  1,  2,  3,  7],
       [10, 12, 14, 16,  8]])

### Class 5
Arrays are multi-dimensional homogenous data-structures (they have got the same data type)

In [199]:
r = [1,3,4,"a"]

In [200]:
np.array(r) #internal type-casting of numeric into character to maintain the homogeneity

array(['1', '3', '4', 'a'], dtype='<U21')

In [201]:
#char > float > int > bool

In [202]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40,  6],
       [ 0,  1,  2,  3,  7],
       [10, 12, 14, 16,  8]])

In [203]:
arr_2d[:2, 2:4] #row numbers 0 and 1 and column numbers 2 and 3

array([[ 3,  4],
       [30, 40]])

In [204]:
arr_2d[:3, 1:]

array([[ 2,  3,  4,  5],
       [20, 30, 40,  6],
       [ 1,  2,  3,  7]])

In [205]:
arr_2d[:4:2, 1:5:2] #row numbers starting from 0 since + ve step size 0th rn, 2nd rn, 
#column numbers - starting from 1, 1+2 

array([[2, 4],
       [1, 3]])

In [206]:
arr_2d[::-1, ::-1]

array([[ 8, 16, 14, 12, 10],
       [ 7,  3,  2,  1,  0],
       [ 6, 40, 30, 20, 10],
       [ 5,  4,  3,  2,  1]])

In [207]:
#Step size is +ve, then by default the beginning index for slicing will be 0 and ending index for slicing will be till the last row /col
#step size -ve, by default the beginning index for slicing will be -1 (last row / col), and ending index will be uptil beginning i.e the first row/col

In [208]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40,  6],
       [ 0,  1,  2,  3,  7],
       [10, 12, 14, 16,  8]])

In [ ]:
arr_2d[::-2, : ] #-1th row, -1-2 row

#### Array Indexing
The result of array indexing is always a flattened array (or 1-d array)

In [224]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40,  6],
       [ 0,  1,  2,  3,  7],
       [10, 12, 14, 16,  8]])

In [227]:
rn = [0,2]
cn = [1,3]
list(zip(rn,cn))

[(0, 1), (2, 3)]

In [228]:
arr_2d[rn, cn]

array([2, 3])

In [245]:
rn = np.arange(arr_2d.shape[0])
cn = np.arange(arr_2d.shape[1]-1)
print(rn, cn)

[0 1 2 3] [0 1 2 3]


In [246]:
np.random.shuffle(rn)
np.random.shuffle(cn)

In [247]:
rn, cn

(array([0, 3, 1, 2]), array([1, 3, 2, 0]))

In [248]:
arr_2d[rn,cn] 

array([ 2, 16, 30,  0])

In [250]:
arr_2d[rn,cn] = 100

In [251]:
arr_2d

array([[  1, 100,   3,   4,   5],
       [ 10,  20, 100,  40,   6],
       [100,   1,   2,   3,   7],
       [ 10,  12,  14, 100,   8]])

In [254]:
arr_2d[0:2, 1] = 1000
arr_2d

array([[   1, 1000,    3,    4,    5],
       [  10, 1000,  100,   40,    6],
       [ 100,    1,    2,    3,    7],
       [  10,   12,   14,  100,    8]])

#### Boolean Indexing

In [256]:
arr_2d>=50

array([[False,  True, False, False, False],
       [False,  True,  True, False, False],
       [ True, False, False, False, False],
       [False, False, False,  True, False]])

In [257]:
arr_2d[arr_2d>=50]

array([1000, 1000,  100,  100,  100])

In [258]:
arr_2d[arr_2d>=50] = 50
arr_2d

array([[ 1, 50,  3,  4,  5],
       [10, 50, 50, 40,  6],
       [50,  1,  2,  3,  7],
       [10, 12, 14, 50,  8]])

#### np.where

In [259]:
np.where(arr_2d>=50) #here the trues are at 0,1; 1,1; 1,2; 2,0; 3,3

(array([0, 1, 1, 2, 3]), array([1, 1, 2, 0, 3]))

In [261]:
a = np.array([100,200,300,400,500])

In [263]:
np.where(a>=300) #index of trues

(array([2, 3, 4]),)

In [ ]:
#where-ever the number of facebook friends is greater than 300 - replace the value by 300

In [264]:
np.where(a>300,300, a)

array([100, 200, 300, 300, 300])

In [268]:
a = a.astype(np.float64)

In [269]:
a[2] = np.nan #np.nan is a float value, so we can't put a float value into an integer array

In [271]:
a[4] = np.nan

In [272]:
a

array([100., 200.,  nan, 400.,  nan])

In [277]:
a = np.where(np.isnan(a), 500, a)

-----

### dtypes

In [214]:
y = np.array([10, 1000000, 100, 1000, 10000, 100000, ])

In [215]:
y.dtype

dtype('int64')

In [217]:
y.prod() #I get a garbage value

3875820019684212736

np.int8 will have 2 pow 8 numbers = 256 numbers 
values ranging from -128 to +127

In [219]:
y=y.astype(np.float64)

In [220]:
y

array([1.e+01, 1.e+06, 1.e+02, 1.e+03, 1.e+04, 1.e+05])

In [221]:
y.prod()

1e+21

In [222]:
y = np.array([10, 1000000, 100, 1000, 10000, 100000], dtype = "float64")
#"float64" can also be written as np.float64

In [223]:
y.prod()

1e+21

----

### Creation of quick arrays

In [210]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [212]:
x = np.ones((2))

In [213]:
x.dtype

dtype('float64')

In [279]:
np.full((2,3), 7, dtype=np.float64)

array([[7., 7., 7.],
       [7., 7., 7.]])

In [280]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [282]:
np.eye(5,6, 2)

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

#### Random number generation functions

In [283]:
np.random.rand(5)

array([0.33628173, 0.53857173, 0.2466292 , 0.78348844, 0.30829854])

In [284]:
np.random.rand(5,2)

array([[0.2085934 , 0.64643445],
       [0.98305355, 0.62094723],
       [0.55441618, 0.85200705],
       [0.99365612, 0.03113449],
       [0.30825363, 0.59045013]])

In [285]:
np.random.rand(2,3,4)

array([[[0.9008451 , 0.29791396, 0.29160365, 0.89207347],
        [0.27733624, 0.18986145, 0.53609924, 0.34023027],
        [0.949626  , 0.54855474, 0.34222508, 0.30768587]],

       [[0.16736555, 0.79718539, 0.48183856, 0.5307079 ],
        [0.48105577, 0.92936182, 0.99901402, 0.72127746],
        [0.27814277, 0.80711452, 0.02292832, 0.71752076]]])

In [286]:
np.random.randn(3) #standard normal distribution has mean = 0 and sd = 1

array([-1.04378325,  1.18927716, -2.55731566])

In [304]:
np.random.seed(100)
np.random.randint(4, 10, 20)

array([4, 4, 7, 4, 6, 8, 6, 9, 6, 6, 6, 5, 4, 4, 8, 7, 8, 6, 4, 7])

In [299]:
np.random.seed(10) #we set the seed in order to be able to replicate the random numbers. The seed can be set to any value.
np.random.randint(4, 10, (2,4))

array([[5, 9, 8, 4],
       [5, 7, 8, 5]])

----

In [305]:
np.linspace(1,200, 200, endpoint=True)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100., 101., 102., 103., 104., 105., 106., 107., 108., 109., 110.,
       111., 112., 113., 114., 115., 116., 117., 118., 119., 120., 121.,
       122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
       133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143.,
       144., 145., 146., 147., 148., 149., 150., 15

In [307]:
a = np.linspace(0,10,9,endpoint=False, retstep = True)

In [308]:
a

(array([0.        , 1.11111111, 2.22222222, 3.33333333, 4.44444444,
        5.55555556, 6.66666667, 7.77777778, 8.88888889]), 1.1111111111111112)

### Revision

In [311]:
var = (1,3,5,9)
for i in var:
    #select the lines of code, and then press ctrl + [ - to dedent the block
    #ctrl+] to indent the block
    print(i)
    print(i+1)

print(var)

1
2
3
4
5
6
9
10
(1, 3, 5, 9)


In [312]:
[i for i in (2,4,5)]

[2, 4, 5]

In [313]:
age=int(input('enter age'))


enter age 5


In [314]:
for i in age:
    print(i)

TypeError: 'int' object is not iterable

---

#### Universal Functions (ufunc)
A universal function is a function that operates on ndarrays in an element-by-element fashion.

In [315]:
b = np.array([[10,20,30],
             [40,50,1]])
b

array([[10, 20, 30],
       [40, 50,  1]])

In [324]:
a = np.array([[0,1,2],[3,4,5]])
a

array([[0, 1, 2],
       [3, 4, 5]])

In [325]:
print(a.shape, b.shape)

(2, 3) (2, 3)


In [326]:
print(a)
print()
print(b)

[[0 1 2]
 [3 4 5]]

[[10 20 30]
 [40 50  1]]


In [320]:
a+b #element wise addition

array([[10, 21, 32],
       [43, 54,  6]])

In [328]:
a = np.array([[10,20,30]])
a

array([[10, 20, 30]])

In [330]:
print(a,"\n\n", b)

[[10 20 30]] 

 [[10 20 30]
 [40 50  1]]


In [331]:
print(a.shape, b.shape)

(1, 3) (2, 3)


In [332]:
a+b
#a has been broadcasted to the shape 2,3 internally by replicating the row and then the addition happens

array([[20, 40, 60],
       [50, 70, 31]])

In [333]:
a = np.array([1,2]).reshape(2,1)
a

array([[1],
       [2]])

In [334]:
print(a,"\n\n", b)

[[1]
 [2]] 

 [[10 20 30]
 [40 50  1]]


In [335]:
a+b

array([[11, 21, 31],
       [42, 52,  3]])

In [ ]:
(1,1) + (3,2)

In [336]:
5 + b

array([[15, 25, 35],
       [45, 55,  6]])

In [338]:
b

array([[10, 20, 30],
       [40, 50,  1]])

In [337]:
[1,2,3] + b #[1,2,3] has been internally converted to an array of 1 row and 3 columns and then broadcasted to 2 rows and 3 cols

array([[11, 22, 33],
       [41, 52,  4]])

In [339]:
[1,2] + b #[1,2] will be converted to an array of 1 row and 2 cols; - dim mismatch with b

ValueError: operands could not be broadcast together with shapes (2,) (2,3) 

In [340]:
np.add(a,b)

array([[11, 21, 31],
       [42, 52,  3]])

In [341]:
np.subtract(a,b)

array([[ -9, -19, -29],
       [-38, -48,   1]])

In [342]:
np.multiply(a,b)

array([[ 10,  20,  30],
       [ 80, 100,   2]])

In [343]:
np.divide(a,b)

array([[0.1       , 0.05      , 0.03333333],
       [0.05      , 0.04      , 2.        ]])

In [ ]:
np.prod() #not a ufunc - does not support broadcasting

In [344]:
b

array([[10, 20, 30],
       [40, 50,  1]])

In [345]:
c = np.array([100,200]).reshape(2,1)
c

array([[100],
       [200]])

In [346]:
c+b

array([[110, 120, 130],
       [240, 250, 201]])

In [347]:
c = np.array([100,200]).reshape(-1,1)
c

array([[100],
       [200]])

In [348]:
np.array([100,200]).reshape(1, -1)

array([[100, 200]])

#### To convert a 2d array into a 1d array

In [349]:
b

array([[10, 20, 30],
       [40, 50,  1]])

In [350]:
b.reshape(6,) #unidimensional array

array([10, 20, 30, 40, 50,  1])

In [352]:
b.flatten()

array([10, 20, 30, 40, 50,  1])

In [353]:
b.ravel()

array([10, 20, 30, 40, 50,  1])

In [355]:
x = a
id(x), id(a)

(139849439426960, 139849439426960)

In [356]:
y = a.copy()

In [357]:
id(y), id(a)

(139849329524528, 139849439426960)

In [360]:
b[b%2!=0]+=9

In [361]:
b

array([[10, 20, 30],
       [40, 50, 10]])

#### Set operations

In [362]:
s1 = np.array(("desk", "chair", "bulb"))

In [363]:
s2 = np.array(("lamp", "bulb", "chair"))

In [364]:
np.intersect1d(s1, s2)

array(['bulb', 'chair'], dtype='<U5')

In [365]:
np.union1d(s1,s2)

array(['bulb', 'chair', 'desk', 'lamp'], dtype='<U5')

#### Statistical Functions
sum, min, max, mean, median, argmin, argmax

In [366]:
b

array([[10, 20, 30],
       [40, 50, 10]])

In [367]:
np.min(b)

10

In [ ]:
#axis = 0 means rows and axis = 1 means columns
#but in statistical functions, axis = 0 - means reduce fn is being applied on rows - rows reduced to 1 row

In [368]:
np.min(b, axis = 0)

array([10, 20, 10])

In [369]:
np.max(b, axis = 0)

array([40, 50, 30])

In [370]:
b

array([[10, 20, 30],
       [40, 50, 10]])

In [371]:
b.mean(axis = 0)

array([25., 35., 20.])

In [372]:
b.mean(axis = 1)#reduce fn will be applied on columns - to reduce the number of cols to 1 

array([20.        , 33.33333333])

In [373]:
b.argmin()

0

In [374]:
b.argmin(axis = 1)

array([0, 2])

In [375]:
b.argmax(axis = 0)

array([1, 1, 0])

---

In [376]:
#Assignment
fruits_to_color = {"watermelon": "green", "pomegranate": "red", "peach": "orange","cherry": "red", "orange": "orange"}
#convert this into colors to fruit - with unique colors on lhs, rhs can have multiple values for the fruits.

In [379]:
c2f = {}
for k,v in fruits_to_color.items():
    c2f[v] = k
c2f

{'green': 'watermelon', 'red': 'cherry', 'orange': 'orange'}

In [380]:
c2f = {}
for fruit,color in fruits_to_color.items():
    if color not in c2f: #if color is not there as a key in c2f dictionary
        c2f[color] = [fruit]
    else: #otherwise append the list with the fruit
        c2f[color].append(fruit)
c2f

{'green': ['watermelon'],
 'red': ['pomegranate', 'cherry'],
 'orange': ['peach', 'orange']}