In [1]:
a = [10,39,90,56,35]

In [3]:
list(enumerate(a))

[(0, 10), (1, 39), (2, 90), (3, 56), (4, 35)]

In [5]:
d = {'a': 1, "b": 2, "c": 5, "d": 6}

In [7]:
list(enumerate(d))

[(0, 'a'), (1, 'b'), (2, 'c'), (3, 'd')]

In [9]:
for index, key in enumerate(d):
    print(index,".", key," : ", d[key], sep = "")

0.a : 1
1.b : 2
2.c : 5
3.d : 6


In [11]:
#Assignment
fruits_to_color = {"watermelon": "green", "pomegranate": "red", "peach": "orange","cherry": "red", "orange": "orange"}
#convert this into colors to fruit - with unique colors on lhs, rhs can have multiple values for the fruits.

{'watermelon': 'green',
 'pomegranate': 'red',
 'peach': 'orange',
 'cherry': 'red',
 'orange': 'orange'}

### lambda fn
one liner functions

In [12]:
def fn(x,y):
    return x+y

In [13]:
fn(4,5)

9

In [14]:
f = lambda x, y: x+y

In [15]:
f(4,5)

9

In [16]:
g = lambda x: x**2

In [1]:
h = lambda x,y,z: (x+y+z)/3

In [2]:
h(1,32, 6)

13.0

In [2]:
i = lambda x,y,z,w: 3*(x**3)+2*(y**2) + z + w**(-1)

### map function
map will map the given function on each element of the iterable

In [3]:
a = lambda x: x**2

In [23]:
lst = [10,20,30]

In [25]:
list(map(a, lst))

[100, 400, 900]

In [27]:
for i in map(lambda x: x**3, lst):
    print(i)

1000
8000
27000


### reduce function
reduce(fun, iterable) will apply to the sequence and it returns a single value

In [ ]:
from functools import reduce

In [32]:
lst.extend([1,5,6,10])

In [33]:
lst

[10, 20, 30, 1, 5, 6, 10]

In [36]:
reduce(lambda x,y: x-y, lst)

-62

Exercise : A store maintains a list of all customers with the customer number and the price of each item purchased by the customer. Find the total amount for each customer using lambda, map reduce 

In [38]:
orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,300.50,650.50)]]

In [42]:
orders[0][0], orders[1][0], orders[2][0]

(1, 2, 3)

In [50]:
[orders[0][0]]+[reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [47]:
reduce(lambda x,y: x+y, orders[1][1])

951.25

In [48]:
reduce(lambda x,y: x+y, orders[2][1])

1351.0

In [50]:
[orders[0][0]]+[reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [54]:
[orders[1][0]]+[reduce(lambda x,y: x+y, orders[1][1])]

[2, 951.25]

In [51]:
#replace orders[0] in the above line by 'a' because we want to map this lambda fn on each component of orders list
f = lambda a: [a[0]]+[reduce(lambda x,y: x+y, a[1])]

In [53]:
list(map(f, orders))

[[1, 1050.5], [2, 951.25], [3, 1351.0]]

----

### List Comprehensions
new_list = [return_value for i in lst]

new_list = [return_Value for i in lst if condition]

new_list = [return value if cond else return_value for i in lst]

In [56]:
l = [i**2 for i in [1,2,3]]
l

[1, 4, 9]

In [58]:
m = [i**10 for i in [10,20,30]]
m

[10000000000, 10240000000000, 590490000000000]

In [60]:
n = [i for i in range(10) if i%2==0]
n

[0, 2, 4, 6, 8]

In [61]:
n = [i**3 for i in range(10) if i%2==0]
n

[0, 8, 64, 216, 512]

In [62]:
o = ["even" if i%2==0 else "odd" for i in lst ]

In [63]:
o

['even', 'even', 'even', 'odd', 'odd', 'even', 'even']

### Zip fn

In [65]:
cost = [.424, .4221, .4228, .413]
cases = [10,20,40,30]

In [66]:
cost*cases

TypeError: can't multiply sequence by non-int of type 'list'

In [68]:
list(zip(cost,cases))

[(0.424, 10), (0.4221, 20), (0.4228, 40), (0.413, 30)]

In [70]:
for x,y in zip(cost, cases):
    print(x*y/sum(cases))

0.0424
0.08442
0.16912
0.12389999999999998


## Importing Libraries
Libraries or packages are the blocks of codes, the programmers have already done the programming, we'll just plug and play those functions.

In [71]:
import numpy

In [72]:
numpy.array([1,3,4])

array([1, 3, 4])

In [73]:
import numpy as np

In [74]:
np.array([1,2,4,5,6])

array([1, 2, 4, 5, 6])

In [75]:
from numpy import *

In [76]:
array([1,2,3,4,5,6])

array([1, 2, 3, 4, 5, 6])

In [77]:
from numpy import array

In [78]:
array([1,3,4,5,6])

array([1, 3, 4, 5, 6])

In [79]:
from functools import reduce

In [80]:
reduce(lambda x,y: x*y, [1,2,3,4,5,6])

720

### To install a library

In [81]:
!pip install keras

In [ ]:
!conda install keras

In [82]:
def fn(x,y):
    return x+y

In [83]:
f = lambda x,y: x+y

In [84]:
fn(3,4)

7

In [85]:
f(3,4)

7

In [86]:
def fn(x):
    return x**2

In [87]:
g = lambda x: x**2

In [90]:
def fn(x):
    return x[0]

In [91]:
fn("Samridhi")

'S'

In [93]:
f = lambda x: x[0]

In [94]:
f("Samridhi")

'S'

Exercise : A store maintains a list of all customers with the customer number and the price of each item purchased by the customer. Find the total amount for each customer using lambda, map reduce 

In [38]:
orders = [[1,(100,500.50,450)],[2,(200,300.75,450.50)],[3,(400,300.50,650.50)]]

In [97]:
[orders[0][0]]

[1]

In [100]:
[reduce(lambda x,y: x+y, orders[0][1])]

[1050.5]

In [101]:
[orders[0][0]] + [reduce(lambda x,y: x+y, orders[0][1])]

[1, 1050.5]

In [102]:
[orders[1][0]] + [reduce(lambda x,y: x+y, orders[1][1])]

[2, 951.25]

In [103]:
[orders[2][0]] + [reduce(lambda x,y: x+y, orders[2][1])]

[3, 1351.0]

In [104]:
f = lambda a: [a[0]] + [reduce(lambda x,y: x+y, a[1])]

In [105]:
f(orders[0])

[1, 1050.5]

In [106]:
f(orders[1])

[2, 951.25]

In [107]:
f(orders[2])

[3, 1351.0]

In [109]:
list(map(f, orders))

[[1, 1050.5], [2, 951.25], [3, 1351.0]]

In [116]:
list(map(lambda x: x**2, [1,2,3]))

[1, 4, 9]

In [110]:
a = ['a','b', 'c']

In [111]:
b = [10,20,30]

In [113]:
list(zip(a,b))

[('a', 10), ('b', 20), ('c', 30)]

In [114]:
for x,y in zip(a,b): #this will iterate over the above list
    print(x*y)

aaaaaaaaaa
bbbbbbbbbbbbbbbbbbbb
cccccccccccccccccccccccccccccc


-----

### Numpy Arrays
- Numeric Python
- There can be character numpy arrays
- But functions like np.max, np.min - will throw exception on character arrays

In [117]:
import numpy as np

In [118]:
a = [1,2,3,4]
b = [10,20,30,40]

In [119]:
a+b #concatenation of lists

[1, 2, 3, 4, 10, 20, 30, 40]

In [121]:
lst = []
for x,y in zip(a,b):
    lst.append(x+y)

In [122]:
lst

[11, 22, 33, 44]

In [123]:
array_a = np.array(a)
array_b = np.array(b)

In [124]:
array_a

array([1, 2, 3, 4])

In [125]:
type(array_a)

numpy.ndarray

In [126]:
array_b

array([10, 20, 30, 40])

In [128]:
array_a + array_b #arrays will support element wise addition / multiplication / division  

array([11, 22, 33, 44])

In [129]:
type(np)

module

In [130]:
array_a.size #number of elements in the array

4

In [131]:
array_a.ndim

1

In [132]:
array_a.shape

(4,)

In [133]:
c = [[1,2,3], [4,5,6]]
arr = np.array(c)

In [134]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [135]:
arr.size

6

In [136]:
arr.shape

(2, 3)

In [137]:
arr.ndim

2

In [138]:
arr_3d = np.array([[[1,3], [2,4], [5,6]], [[10,20],[2,3], [4,5]]])

In [139]:
arr_3d

array([[[ 1,  3],
        [ 2,  4],
        [ 5,  6]],

       [[10, 20],
        [ 2,  3],
        [ 4,  5]]])

In [140]:
arr_3d.shape

(2, 3, 2)

In [143]:
arr_2d = np.array([array_a, array_b])

In [144]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [145]:
arr_2d[0,0]

1

In [146]:
arr_2d[-1,-1]

40

In [148]:
arr_2d[1, 2], arr_2d[-1, -2]

(30, 30)

In [149]:
arr_2d[-1, -3]

20

In [150]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [160]:
arr_2d=np.concatenate([arr_2d, np.array([range(4)]), np.array([range(10, 18, 2)])], axis = 0)
#axis = 0 row-wise concatenation
#axis = 1 col-wise concatenation

In [166]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [ 0,  1,  2,  3],
       [10, 12, 14, 16]])

In [154]:
list(range(4))

[0, 1, 2, 3]

In [156]:
np.array([range(4)])

array([[0, 1, 2, 3]])

In [157]:
list(range(10,18,2)) 

[10, 12, 14, 16]

In [159]:
np.array([range(10,18,2)])

array([[10, 12, 14, 16]])

In [162]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [164]:
np.array(range(10,18,2))

array([10, 12, 14, 16])

In [165]:
np.arange(10, 18, 2)

array([10, 12, 14, 16])

In [167]:
arr_2d

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40],
       [ 0,  1,  2,  3],
       [10, 12, 14, 16]])

In [170]:
x = np.arange(5,9,1)
x

array([5, 6, 7, 8])

In [173]:
x=x.reshape(4,1)
x

array([[5],
       [6],
       [7],
       [8]])

In [175]:
arr_2d = np.concatenate([arr_2d, x], axis = 1)

In [176]:
arr_2d

array([[ 1,  2,  3,  4,  5],
       [10, 20, 30, 40,  6],
       [ 0,  1,  2,  3,  7],
       [10, 12, 14, 16,  8]])